plugins:  
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

rules:
  no-console: 0
  import/extensions: 0